version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: aiuser
      POSTGRES_PASSWORD: aiuserpasswd
      POSTGRES_DB: aidb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aiuser -d aidb"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres-data: