spring:
  application:
    admin:
      jmx-name: spring-ai-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/aidb
    username: aiuser
    password: aiuserpasswd
  jpa:
    hibernate:
      ddl-auto: update
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000